language: ruby
rvm:
 - 2.1

# install jekyll 
before_script:
 - gem install jekyll

script: jekyll build

# branch whitelist
branches:
  only:
  - master     # test the gh-pages branch
 

env:
 - secure:""