# Site settings
title: Hello there!
email: 
description: ""
baseurl: ""
url: ""
twitter_username: nealxyc
github_username:  nealxyc

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  input: GFM

# Deployment temp files
exclude: [deploy.sh, deploy, credential]
 
# post format
defaults:
  -
    scope:
      path: "_posts"
      type: "post"
    values:
      layout: "post"
