# Site settings
title: Hello there!
email: 
description: ""
baseurl: ""
url: ""
twitter_username: nealxyc
github_username:  nealxyc

# Build settings
markdown: kramdown
permalink: pretty

# kramdown config
kramdown:
  input: GFM
  coderay_line_numbers: nil

# Deployment temp files
exclude: [deploy.sh, deploy, credential, cred]
 
# post format
defaults:
  -
    scope:
      path: "_posts"
      type: "post"
    values:
      layout: "post"
